application: spicolis-dev
version: 1
runtime: python27
api_version: 1
threadsafe: true

skip_files: |
 ^(.*/)?(
 (app\.yaml)|
 (app\.yml)|
 (index\.yaml)|
 (index\.yml)|
 (#.*#)|
 (.*~)|
 (.*\.py[co])|
 (.*/RCS/.*)|
 (\..*)|
 (local/.*)|
 (settingslocal\.py)|
 (.git)|
 (.gitignore)|
 (.ropeproject)|
 (assets)|
 )$

libraries:
- name: jinja2
  version: "2.6"
- name: lxml
  version: "2.3"

inbound_services:
- warmup

builtins:
- appstats: on
- remote_api: on

admin_console:
  pages:
  - name: Appstats
    url: /_ah/stats/

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: bootstrap.app
